SERVICE_TITLE = Graph Database Service
SERVICE_NAME = graphdbs

FRAMEWORK_ROOT_REL = ../..
FRAMEWORK_ROOT := $(abspath $(FRAMEWORK_ROOT_REL))

include $(FRAMEWORK_ROOT)/.Makefile.inherit

# Placeholder for future provider integration
