SERVICE_TITLE = Distributed Tracing Service
SERVICE_NAME = tracers

FRAMEWORK_ROOT_REL = ../..
FRAMEWORK_ROOT := $(abspath $(FRAMEWORK_ROOT_REL))

include $(FRAMEWORK_ROOT)/.Makefile.inherit

# Placeholder for future provider integration
