SERVICE_TITLE = Metrics Collector Service
SERVICE_NAME = collectors

FRAMEWORK_ROOT_REL = ../..
FRAMEWORK_ROOT := $(abspath $(FRAMEWORK_ROOT_REL))

include $(FRAMEWORK_ROOT)/.Makefile.inherit

# Placeholder for future provider integration
