SERVICE_TITLE = Time-Series Database Service
SERVICE_NAME = tsdbs

FRAMEWORK_ROOT_REL = ../..
FRAMEWORK_ROOT := $(abspath $(FRAMEWORK_ROOT_REL))

include $(FRAMEWORK_ROOT)/.Makefile.inherit

# Placeholder for future provider integration
