SERVICE_TITLE = Secrets Management Service
SERVICE_NAME = secrets

FRAMEWORK_ROOT_REL = ../..
FRAMEWORK_ROOT := $(abspath $(FRAMEWORK_ROOT_REL))

include $(FRAMEWORK_ROOT)/.Makefile.inherit

# Placeholder for future provider integration
